global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Text;
global using FashionWeekLibrary.Entiteti;
global using FashionWeekLibrary.DTOs;
global using NHibernate;
global using static FashionWeekLibrary.Extensions;
global using System.Diagnostics.CodeAnalysis;